### ISSUE TITLE
pause is not working

### ISSUE THREAD

**Issue by PrashantTapase** [kswedberg/jquery-carousel-lite#48]
$('div.carousel').trigger('pauseCarousel'); is not working. Did u tested before documentation

**Comment by kswedberg** [comment]
Works for me. I just added pause and resume buttons for the first carousel in the demo:
https://kswedberg.github.io/jquery-carousel-lite/demo/

No problems there. If it still doesn't work for you, please provide more information. Thanks!

**Comment by kswedberg** [comment]
Closing due to lack of answer from @PrashantTapase .
