### ISSUE TITLE
unregister this package from bower 'jcarousellite' name

### ISSUE THREAD

**Issue by gigmaps** [kswedberg/jquery-carousel-lite#49]
Firstly, thanks for your work in keeping @ganeshmax 's original jcarousellite plugin up-to-date
and with better documentation.

However, it's misleading to have this plugin registered in bower under both:
- jquery-carousel-lite (which is the correct bower registry name)
AND
- jcarousellite (which should be registered to to the original jcarousellite https://github.com/ganeshmax/jcarousellite/blob/master/bower.json)

It was possibly a 3rd party who registered the 'jcarousellite' name to this repo - but either way it's problematic since it's effectively two different plugins, not the name of this repo / plugin, uses different variables to the original - and is squatting on the original 'jcarousellite' name.

Can you please unregister this package in bower from the 'jcarousellite' name ?

many thanks.

**Comment by kswedberg** [comment]
Makes sense. Will do as soon as I can.

**Comment by kswedberg** [comment]
Okay, I've unregistered "jcarousellite." You might want to contact @ganeshmax and ask him to register it. I hope this doesn't mess up a lot of projects that were depending on it.

**Comment by gigmaps** [comment]
thanks for that
i've registered the 'jcarousellite' name to https://github.com/ganeshmax/jcarousellite.git

**Comment by kswedberg** [comment]
Excellent! Thanks for calling this to my attention.
