### ISSUE TITLE
Error after installation via bower

### ISSUE THREAD

**Issue by jannovy** [kswedberg/jquery-carousel-lite#51]
Hi, I have some issues with installation via bower:

bower install jcarousellite#1.9.3

bower jcarousellite#1.9.3   not-cached https://github.com/ganeshmax/jcarousellite.git#1.9.3
bower jcarousellite#1.9.3      resolve https://github.com/ganeshmax/jcarousellite.git#1.9.3
bower jcarousellite#1.9.3 ENORESTARGET No tag found that was able to satisfy 1.9.3

No files were downloaded.

After

bower install jcarousellite

bower jcarousellite#\*       not-cached https://github.com/ganeshmax/jcarousellite.git#*
bower jcarousellite#\*          resolve https://github.com/ganeshmax/jcarousellite.git#*
bower jcarousellite#\*         checkout master
bower jcarousellite#\*         resolved https://github.com/ganeshmax/jcarousellite.git#fceadf8c4d

I get files from complete different repository (https://github.com/ganeshmax/jcarousellite.git)

**Comment by jannovy** [comment]
Ok, I try 

bower install jquery-carousel-lite

and get to right files. But please check https://libraries.io/bower/jcarousellite

**Comment by kswedberg** [comment]
Sorry about that. Not sure what I can do about the libraries.io listing. See https://github.com/kswedberg/jquery-carousel-lite/issues/49 for context.

**Comment by jannovy** [comment]
Thank you for the context, I see what happend now :-) May be you can just update your readme.md with Bower installation.

**Comment by kswedberg** [comment]
Yeah, good idea. I'll do that. Need to update stuff on npm, too, I suppose.

**Comment by philippsander** [comment]
I still get that problem.

bower install jcarousellite fetches version 1.1

**Comment by kswedberg** [comment]
@philippsander , that's right. That's the latest version in Ganeshji Marwaha's repo. If you want my repo, try this: `bower install jquery-carousel-lite`

**Comment by kswedberg** [comment]
I contacted libraries.io to ask them to update their page for jcarousellite, and I added installation instructions to this readme doc, so I'm hoping that is sufficient to close this issue.
